name: aria2
enable: true
priority: 4
height: 6
padding: 3
extend:
  HostPort:
    val: "http://192.168.100.4:6800/jsonrpc"
    desc: 接口
    priority: 200
  Token:
    val: "test"
    desc: 密钥
    priority: 200