name: docker
enable: true
priority: 80
height: 6
padding: 3
support_widget: true
extend:
  HostPort:
    val: "http://127.0.0.1:6666"
    desc: 接口
    priority: 200
  Limit:
    val: "20"
    desc: 分页大小
    priority: 180